/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, email: {
                    name: "email",
                    type: "String",
                }, emailVerified: {
                    name: "emailVerified",
                    type: "Boolean",
                }, image: {
                    name: "image",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                }, sessions: {
                    name: "sessions",
                    type: "Session",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, accounts: {
                    name: "accounts",
                    type: "Account",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, members: {
                    name: "members",
                    type: "Member",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, invitations: {
                    name: "invitations",
                    type: "Invitation",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, assignedTasks: {
                    name: "assignedTasks",
                    type: "Task",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'assignee',
                }, ownedBoards: {
                    name: "ownedBoards",
                    type: "Board",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'owner',
                }, userBoards: {
                    name: "userBoards",
                    type: "Board",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'users',
                }, authoredPosts: {
                    name: "authoredPosts",
                    type: "Post",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'author',
                }, createdWorkflows: {
                    name: "createdWorkflows",
                    type: "Workflow",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, triggeredExecutions: {
                    name: "triggeredExecutions",
                    type: "WorkflowExecution",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'triggeredByUser',
                }, composioConnections: {
                    name: "composioConnections",
                    type: "ComposioConnection",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, role: {
                    name: "role",
                    type: "String",
                    isOptional: true,
                }, banned: {
                    name: "banned",
                    type: "Boolean",
                    isOptional: true,
                }, banReason: {
                    name: "banReason",
                    type: "String",
                    isOptional: true,
                }, banExpires: {
                    name: "banExpires",
                    type: "DateTime",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            },
        },
        session: {
            name: 'Session', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, token: {
                    name: "token",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                }, ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    isOptional: true,
                }, userAgent: {
                    name: "userAgent",
                    type: "String",
                    isOptional: true,
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'sessions',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, activeOrganizationId: {
                    name: "activeOrganizationId",
                    type: "String",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, token: {
                    name: "token",
                    fields: ["token"]
                },
            },
        },
        account: {
            name: 'Account', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, accountId: {
                    name: "accountId",
                    type: "String",
                }, providerId: {
                    name: "providerId",
                    type: "String",
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'accounts',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, accessToken: {
                    name: "accessToken",
                    type: "String",
                    isOptional: true,
                }, refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    isOptional: true,
                }, idToken: {
                    name: "idToken",
                    type: "String",
                    isOptional: true,
                }, accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    isOptional: true,
                }, refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    isOptional: true,
                }, scope: {
                    name: "scope",
                    type: "String",
                    isOptional: true,
                }, password: {
                    name: "password",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        verification: {
            name: 'Verification', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, identifier: {
                    name: "identifier",
                    type: "String",
                }, value: {
                    name: "value",
                    type: "String",
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    isOptional: true,
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        organization: {
            name: 'Organization', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, slug: {
                    name: "slug",
                    type: "String",
                    isOptional: true,
                }, logo: {
                    name: "logo",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                }, metadata: {
                    name: "metadata",
                    type: "String",
                    isOptional: true,
                }, members: {
                    name: "members",
                    type: "Member",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                }, invitations: {
                    name: "invitations",
                    type: "Invitation",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                }, boards: {
                    name: "boards",
                    type: "Board",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                }, workflows: {
                    name: "workflows",
                    type: "Workflow",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                }, workflowTriggers: {
                    name: "workflowTriggers",
                    type: "WorkflowTrigger",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                }, workflowExecutions: {
                    name: "workflowExecutions",
                    type: "WorkflowExecution",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                }, composioConnections: {
                    name: "composioConnections",
                    type: "ComposioConnection",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        member: {
            name: 'Member', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'organization',
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'members',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "organizationId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'members',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, role: {
                    name: "role",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        invitation: {
            name: 'Invitation', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'organization',
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'invitations',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "organizationId" },
                }, email: {
                    name: "email",
                    type: "String",
                }, role: {
                    name: "role",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "String",
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, inviterId: {
                    name: "inviterId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'invitations',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "inviterId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        board: {
            name: 'Board', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'boards',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "organizationId" },
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    defaultValueProvider: $default$Board$organizationId,
                    isForeignKey: true,
                    relationField: 'organization',
                }, owner: {
                    name: "owner",
                    type: "User",
                    isDataModel: true,
                    backLink: 'ownedBoards',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "ownerId" },
                }, ownerId: {
                    name: "ownerId",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    defaultValueProvider: $default$Board$ownerId,
                    isForeignKey: true,
                    relationField: 'owner',
                }, columns: {
                    name: "columns",
                    type: "Column",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'board',
                }, users: {
                    name: "users",
                    type: "User",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'userBoards',
                }, workflowTriggers: {
                    name: "workflowTriggers",
                    type: "WorkflowTrigger",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'board',
                }, workflowExecutions: {
                    name: "workflowExecutions",
                    type: "WorkflowExecution",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'board',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        column: {
            name: 'Column', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, title: {
                    name: "title",
                    type: "String",
                }, order: {
                    name: "order",
                    type: "Int",
                }, board: {
                    name: "board",
                    type: "Board",
                    isDataModel: true,
                    backLink: 'columns',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "boardId" },
                }, boardId: {
                    name: "boardId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'board',
                }, tasks: {
                    name: "tasks",
                    type: "Task",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'column',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        task: {
            name: 'Task', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, title: {
                    name: "title",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, priority: {
                    name: "priority",
                    type: "Priority",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, order: {
                    name: "order",
                    type: "Int",
                }, column: {
                    name: "column",
                    type: "Column",
                    isDataModel: true,
                    backLink: 'tasks',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "columnId" },
                }, columnId: {
                    name: "columnId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'column',
                }, assignee: {
                    name: "assignee",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'assignedTasks',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "assigneeId" },
                }, assigneeId: {
                    name: "assigneeId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'assignee',
                }, completedAt: {
                    name: "completedAt",
                    type: "DateTime",
                    isOptional: true,
                }, isArchived: {
                    name: "isArchived",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        tag: {
            name: 'Tag', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, slug: {
                    name: "slug",
                    type: "String",
                }, color: {
                    name: "color",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, posts: {
                    name: "posts",
                    type: "PostTag",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'tag',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        postTag: {
            name: 'PostTag', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, post: {
                    name: "post",
                    type: "Post",
                    isDataModel: true,
                    backLink: 'tags',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "postId" },
                }, postId: {
                    name: "postId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'post',
                }, tag: {
                    name: "tag",
                    type: "Tag",
                    isDataModel: true,
                    backLink: 'posts',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "tagId" },
                }, tagId: {
                    name: "tagId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'tag',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, postId_tagId: {
                    name: "postId_tagId",
                    fields: ["postId", "tagId"]
                },
            },
        },
        post: {
            name: 'Post', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, title: {
                    name: "title",
                    type: "String",
                }, content: {
                    name: "content",
                    type: "String",
                }, excerpt: {
                    name: "excerpt",
                    type: "String",
                }, featuredImage: {
                    name: "featuredImage",
                    type: "String",
                    isOptional: true,
                }, slug: {
                    name: "slug",
                    type: "String",
                }, published: {
                    name: "published",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, publishedAt: {
                    name: "publishedAt",
                    type: "DateTime",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, author: {
                    name: "author",
                    type: "User",
                    isDataModel: true,
                    backLink: 'authoredPosts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "authorId" },
                }, authorId: {
                    name: "authorId",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    defaultValueProvider: $default$Post$authorId,
                    isForeignKey: true,
                    relationField: 'author',
                }, tags: {
                    name: "tags",
                    type: "PostTag",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'post',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        workflow: {
            name: 'Workflow', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "WorkflowStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, nodesJson: {
                    name: "nodesJson",
                    type: "Json",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "[]" }] }],
                }, edgesJson: {
                    name: "edgesJson",
                    type: "Json",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "[]" }] }],
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'workflows',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "organizationId" },
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    defaultValueProvider: $default$Workflow$organizationId,
                    isForeignKey: true,
                    relationField: 'organization',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    backLink: 'createdWorkflows',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "createdById" },
                }, createdById: {
                    name: "createdById",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    defaultValueProvider: $default$Workflow$createdById,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, triggers: {
                    name: "triggers",
                    type: "WorkflowTrigger",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'workflow',
                }, executions: {
                    name: "executions",
                    type: "WorkflowExecution",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'workflow',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        workflowTrigger: {
            name: 'WorkflowTrigger', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'workflowTriggers',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "organizationId" },
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    defaultValueProvider: $default$WorkflowTrigger$organizationId,
                    isForeignKey: true,
                    relationField: 'organization',
                }, workflow: {
                    name: "workflow",
                    type: "Workflow",
                    isDataModel: true,
                    backLink: 'triggers',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "workflowId" },
                }, workflowId: {
                    name: "workflowId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'workflow',
                }, board: {
                    name: "board",
                    type: "Board",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'workflowTriggers',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "boardId" },
                }, boardId: {
                    name: "boardId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'board',
                }, triggerType: {
                    name: "triggerType",
                    type: "TriggerType",
                }, configJson: {
                    name: "configJson",
                    type: "Json",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "{}" }] }],
                }, enabled: {
                    name: "enabled",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, executions: {
                    name: "executions",
                    type: "WorkflowExecution",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'trigger',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        workflowExecution: {
            name: 'WorkflowExecution', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'workflowExecutions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "organizationId" },
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    defaultValueProvider: $default$WorkflowExecution$organizationId,
                    isForeignKey: true,
                    relationField: 'organization',
                }, workflow: {
                    name: "workflow",
                    type: "Workflow",
                    isDataModel: true,
                    backLink: 'executions',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "workflowId" },
                }, workflowId: {
                    name: "workflowId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'workflow',
                }, board: {
                    name: "board",
                    type: "Board",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'workflowExecutions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "boardId" },
                }, boardId: {
                    name: "boardId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'board',
                }, cardId: {
                    name: "cardId",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "ExecutionStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, inputJson: {
                    name: "inputJson",
                    type: "Json",
                    isOptional: true,
                }, outputJson: {
                    name: "outputJson",
                    type: "Json",
                    isOptional: true,
                }, error: {
                    name: "error",
                    type: "String",
                    isOptional: true,
                }, triggeredByUser: {
                    name: "triggeredByUser",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'triggeredExecutions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "triggeredByUserId" },
                }, triggeredByUserId: {
                    name: "triggeredByUserId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'triggeredByUser',
                }, trigger: {
                    name: "trigger",
                    type: "WorkflowTrigger",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'executions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "triggerId" },
                }, triggerId: {
                    name: "triggerId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'trigger',
                }, startedAt: {
                    name: "startedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, completedAt: {
                    name: "completedAt",
                    type: "DateTime",
                    isOptional: true,
                }, logs: {
                    name: "logs",
                    type: "WorkflowExecutionLog",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'execution',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        workflowExecutionLog: {
            name: 'WorkflowExecutionLog', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, execution: {
                    name: "execution",
                    type: "WorkflowExecution",
                    isDataModel: true,
                    backLink: 'logs',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "executionId" },
                }, executionId: {
                    name: "executionId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'execution',
                }, nodeId: {
                    name: "nodeId",
                    type: "String",
                }, nodeName: {
                    name: "nodeName",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "LogStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, inputJson: {
                    name: "inputJson",
                    type: "Json",
                    isOptional: true,
                }, outputJson: {
                    name: "outputJson",
                    type: "Json",
                    isOptional: true,
                }, error: {
                    name: "error",
                    type: "String",
                    isOptional: true,
                }, startedAt: {
                    name: "startedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, completedAt: {
                    name: "completedAt",
                    type: "DateTime",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        composioConnection: {
            name: 'ComposioConnection', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'composioConnections',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "organizationId" },
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    defaultValueProvider: $default$ComposioConnection$organizationId,
                    isForeignKey: true,
                    relationField: 'organization',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'composioConnections',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    defaultValueProvider: $default$ComposioConnection$userId,
                    isForeignKey: true,
                    relationField: 'user',
                }, appName: {
                    name: "appName",
                    type: "String",
                }, composioEntityId: {
                    name: "composioEntityId",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "ConnectionStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, organizationId_userId_appName: {
                    name: "organizationId_userId_appName",
                    fields: ["organizationId", "userId", "appName"]
                },
            },
        },

    },
    typeDefs: {
        auth: {
            name: 'Auth', fields: {
                userId: {
                    name: "userId",
                    type: "String",
                }, userRole: {
                    name: "userRole",
                    type: "String",
                    isOptional: true,
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isOptional: true,
                }, organizationRole: {
                    name: "organizationRole",
                    type: "String",
                    isOptional: true,
                },
            },
        },

    },
    deleteCascade: {
        user: ['Session', 'Account', 'Member', 'Invitation'],
        organization: ['Member', 'Invitation'],
        board: ['Column'],
        column: ['Task'],
        tag: ['PostTag'],
        post: ['PostTag'],
        workflow: ['WorkflowTrigger', 'WorkflowExecution'],
        workflowExecution: ['WorkflowExecutionLog'],

    },
    authModel: 'Auth'

};

function $default$Board$organizationId(user: any): unknown {
    return user?.organizationId;
}

function $default$Board$ownerId(user: any): unknown {
    return user?.userId;
}

function $default$Post$authorId(user: any): unknown {
    return user?.userId;
}

function $default$Workflow$organizationId(user: any): unknown {
    return user?.organizationId;
}

function $default$Workflow$createdById(user: any): unknown {
    return user?.userId;
}

function $default$WorkflowTrigger$organizationId(user: any): unknown {
    return user?.organizationId;
}

function $default$WorkflowExecution$organizationId(user: any): unknown {
    return user?.organizationId;
}

function $default$ComposioConnection$organizationId(user: any): unknown {
    return user?.organizationId;
}

function $default$ComposioConnection$userId(user: any): unknown {
    return user?.userId;
}
export default metadata;
