/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, ComposioConnection } from "@zenstackhq/runtime/models";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateComposioConnection(options?: Omit<(UseMutationOptions<(ComposioConnection | undefined), DefaultError, Prisma.ComposioConnectionCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ComposioConnectionCreateArgs, DefaultError, ComposioConnection, true>('ComposioConnection', 'POST', `${endpoint}/composioConnection/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ComposioConnectionCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ComposioConnectionCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ComposioConnection, Prisma.ComposioConnectionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ComposioConnectionCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ComposioConnection, Prisma.ComposioConnectionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyComposioConnection(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ComposioConnectionCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ComposioConnectionCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ComposioConnection', 'POST', `${endpoint}/composioConnection/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ComposioConnectionCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ComposioConnectionCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ComposioConnectionCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyComposioConnection<TArgs extends Prisma.ComposioConnectionFindManyArgs, TQueryFnData = Array<Prisma.ComposioConnectionGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/findMany`, args, options, fetch);
}

export function useInfiniteFindManyComposioConnection<TArgs extends Prisma.ComposioConnectionFindManyArgs, TQueryFnData = Array<Prisma.ComposioConnectionGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/findMany`, args, options, fetch);
}

export function useSuspenseFindManyComposioConnection<TArgs extends Prisma.ComposioConnectionFindManyArgs, TQueryFnData = Array<Prisma.ComposioConnectionGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyComposioConnection<TArgs extends Prisma.ComposioConnectionFindManyArgs, TQueryFnData = Array<Prisma.ComposioConnectionGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/findMany`, args, options, fetch);
}

export function useFindUniqueComposioConnection<TArgs extends Prisma.ComposioConnectionFindUniqueArgs, TQueryFnData = Prisma.ComposioConnectionGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueComposioConnection<TArgs extends Prisma.ComposioConnectionFindUniqueArgs, TQueryFnData = Prisma.ComposioConnectionGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/findUnique`, args, options, fetch);
}

export function useFindFirstComposioConnection<TArgs extends Prisma.ComposioConnectionFindFirstArgs, TQueryFnData = Prisma.ComposioConnectionGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstComposioConnection<TArgs extends Prisma.ComposioConnectionFindFirstArgs, TQueryFnData = Prisma.ComposioConnectionGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/findFirst`, args, options, fetch);
}

export function useUpdateComposioConnection(options?: Omit<(UseMutationOptions<(ComposioConnection | undefined), DefaultError, Prisma.ComposioConnectionUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ComposioConnectionUpdateArgs, DefaultError, ComposioConnection, true>('ComposioConnection', 'PUT', `${endpoint}/composioConnection/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ComposioConnectionUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ComposioConnectionUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ComposioConnection, Prisma.ComposioConnectionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ComposioConnectionUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ComposioConnection, Prisma.ComposioConnectionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyComposioConnection(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ComposioConnectionUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ComposioConnectionUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ComposioConnection', 'PUT', `${endpoint}/composioConnection/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ComposioConnectionUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ComposioConnectionUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ComposioConnectionUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertComposioConnection(options?: Omit<(UseMutationOptions<(ComposioConnection | undefined), DefaultError, Prisma.ComposioConnectionUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ComposioConnectionUpsertArgs, DefaultError, ComposioConnection, true>('ComposioConnection', 'POST', `${endpoint}/composioConnection/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ComposioConnectionUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ComposioConnectionUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ComposioConnection, Prisma.ComposioConnectionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ComposioConnectionUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ComposioConnection, Prisma.ComposioConnectionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteComposioConnection(options?: Omit<(UseMutationOptions<(ComposioConnection | undefined), DefaultError, Prisma.ComposioConnectionDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ComposioConnectionDeleteArgs, DefaultError, ComposioConnection, true>('ComposioConnection', 'DELETE', `${endpoint}/composioConnection/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ComposioConnectionDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ComposioConnectionDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ComposioConnection, Prisma.ComposioConnectionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ComposioConnectionDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ComposioConnection, Prisma.ComposioConnectionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyComposioConnection(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ComposioConnectionDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ComposioConnectionDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ComposioConnection', 'DELETE', `${endpoint}/composioConnection/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ComposioConnectionDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ComposioConnectionDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ComposioConnectionDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateComposioConnection<TArgs extends Prisma.ComposioConnectionAggregateArgs, TQueryFnData = Prisma.GetComposioConnectionAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateComposioConnection<TArgs extends Prisma.ComposioConnectionAggregateArgs, TQueryFnData = Prisma.GetComposioConnectionAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/aggregate`, args, options, fetch);
}

export function useGroupByComposioConnection<TArgs extends Prisma.ComposioConnectionGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ComposioConnectionGroupByArgs['orderBy'] } : { orderBy?: Prisma.ComposioConnectionGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ComposioConnectionGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ComposioConnectionGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ComposioConnectionGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ComposioConnectionGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ComposioConnectionGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByComposioConnection<TArgs extends Prisma.ComposioConnectionGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ComposioConnectionGroupByArgs['orderBy'] } : { orderBy?: Prisma.ComposioConnectionGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ComposioConnectionGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ComposioConnectionGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ComposioConnectionGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ComposioConnectionGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ComposioConnectionGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/groupBy`, args, options, fetch);
}

export function useCountComposioConnection<TArgs extends Prisma.ComposioConnectionCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ComposioConnectionCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/count`, args, options, fetch);
}

export function useSuspenseCountComposioConnection<TArgs extends Prisma.ComposioConnectionCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ComposioConnectionCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ComposioConnectionCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ComposioConnection', `${endpoint}/composioConnection/count`, args, options, fetch);
}
import type { ConnectionStatus } from '@zenstackhq/runtime/models';

export function useCheckComposioConnection<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; organizationId?: string; userId?: string; appName?: string; composioEntityId?: string; status?: ConnectionStatus }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ComposioConnection', `${endpoint}/composioConnection/check`, args, options, fetch);
}
