/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, WorkflowExecutionLog } from "@zenstackhq/runtime/models";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateWorkflowExecutionLog(options?: Omit<(UseMutationOptions<(WorkflowExecutionLog | undefined), DefaultError, Prisma.WorkflowExecutionLogCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowExecutionLogCreateArgs, DefaultError, WorkflowExecutionLog, true>('WorkflowExecutionLog', 'POST', `${endpoint}/workflowExecutionLog/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowExecutionLogCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkflowExecutionLog, Prisma.WorkflowExecutionLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkflowExecutionLog, Prisma.WorkflowExecutionLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyWorkflowExecutionLog(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WorkflowExecutionLogCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowExecutionLogCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('WorkflowExecutionLog', 'POST', `${endpoint}/workflowExecutionLog/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowExecutionLogCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogFindManyArgs, TQueryFnData = Array<Prisma.WorkflowExecutionLogGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/findMany`, args, options, fetch);
}

export function useInfiniteFindManyWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogFindManyArgs, TQueryFnData = Array<Prisma.WorkflowExecutionLogGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/findMany`, args, options, fetch);
}

export function useSuspenseFindManyWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogFindManyArgs, TQueryFnData = Array<Prisma.WorkflowExecutionLogGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogFindManyArgs, TQueryFnData = Array<Prisma.WorkflowExecutionLogGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/findMany`, args, options, fetch);
}

export function useFindUniqueWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogFindUniqueArgs, TQueryFnData = Prisma.WorkflowExecutionLogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogFindUniqueArgs, TQueryFnData = Prisma.WorkflowExecutionLogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/findUnique`, args, options, fetch);
}

export function useFindFirstWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogFindFirstArgs, TQueryFnData = Prisma.WorkflowExecutionLogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogFindFirstArgs, TQueryFnData = Prisma.WorkflowExecutionLogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/findFirst`, args, options, fetch);
}

export function useUpdateWorkflowExecutionLog(options?: Omit<(UseMutationOptions<(WorkflowExecutionLog | undefined), DefaultError, Prisma.WorkflowExecutionLogUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowExecutionLogUpdateArgs, DefaultError, WorkflowExecutionLog, true>('WorkflowExecutionLog', 'PUT', `${endpoint}/workflowExecutionLog/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowExecutionLogUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkflowExecutionLog, Prisma.WorkflowExecutionLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkflowExecutionLog, Prisma.WorkflowExecutionLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyWorkflowExecutionLog(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WorkflowExecutionLogUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowExecutionLogUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('WorkflowExecutionLog', 'PUT', `${endpoint}/workflowExecutionLog/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowExecutionLogUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertWorkflowExecutionLog(options?: Omit<(UseMutationOptions<(WorkflowExecutionLog | undefined), DefaultError, Prisma.WorkflowExecutionLogUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowExecutionLogUpsertArgs, DefaultError, WorkflowExecutionLog, true>('WorkflowExecutionLog', 'POST', `${endpoint}/workflowExecutionLog/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowExecutionLogUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkflowExecutionLog, Prisma.WorkflowExecutionLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkflowExecutionLog, Prisma.WorkflowExecutionLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteWorkflowExecutionLog(options?: Omit<(UseMutationOptions<(WorkflowExecutionLog | undefined), DefaultError, Prisma.WorkflowExecutionLogDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowExecutionLogDeleteArgs, DefaultError, WorkflowExecutionLog, true>('WorkflowExecutionLog', 'DELETE', `${endpoint}/workflowExecutionLog/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowExecutionLogDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkflowExecutionLog, Prisma.WorkflowExecutionLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkflowExecutionLog, Prisma.WorkflowExecutionLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyWorkflowExecutionLog(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WorkflowExecutionLogDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowExecutionLogDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('WorkflowExecutionLog', 'DELETE', `${endpoint}/workflowExecutionLog/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowExecutionLogDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowExecutionLogDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogAggregateArgs, TQueryFnData = Prisma.GetWorkflowExecutionLogAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogAggregateArgs, TQueryFnData = Prisma.GetWorkflowExecutionLogAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/aggregate`, args, options, fetch);
}

export function useGroupByWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WorkflowExecutionLogGroupByArgs['orderBy'] } : { orderBy?: Prisma.WorkflowExecutionLogGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WorkflowExecutionLogGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WorkflowExecutionLogGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkflowExecutionLogGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkflowExecutionLogGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WorkflowExecutionLogGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WorkflowExecutionLogGroupByArgs['orderBy'] } : { orderBy?: Prisma.WorkflowExecutionLogGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WorkflowExecutionLogGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WorkflowExecutionLogGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkflowExecutionLogGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkflowExecutionLogGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WorkflowExecutionLogGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/groupBy`, args, options, fetch);
}

export function useCountWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WorkflowExecutionLogCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/count`, args, options, fetch);
}

export function useSuspenseCountWorkflowExecutionLog<TArgs extends Prisma.WorkflowExecutionLogCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WorkflowExecutionLogCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowExecutionLogCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/count`, args, options, fetch);
}
import type { LogStatus } from '@zenstackhq/runtime/models';

export function useCheckWorkflowExecutionLog<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; executionId?: string; nodeId?: string; nodeName?: string; status?: LogStatus; error?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('WorkflowExecutionLog', `${endpoint}/workflowExecutionLog/check`, args, options, fetch);
}
