/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, WorkflowTrigger } from "@zenstackhq/runtime/models";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateWorkflowTrigger(options?: Omit<(UseMutationOptions<(WorkflowTrigger | undefined), DefaultError, Prisma.WorkflowTriggerCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowTriggerCreateArgs, DefaultError, WorkflowTrigger, true>('WorkflowTrigger', 'POST', `${endpoint}/workflowTrigger/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowTriggerCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowTriggerCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkflowTrigger, Prisma.WorkflowTriggerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowTriggerCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkflowTrigger, Prisma.WorkflowTriggerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyWorkflowTrigger(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WorkflowTriggerCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowTriggerCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('WorkflowTrigger', 'POST', `${endpoint}/workflowTrigger/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowTriggerCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowTriggerCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowTriggerCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerFindManyArgs, TQueryFnData = Array<Prisma.WorkflowTriggerGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/findMany`, args, options, fetch);
}

export function useInfiniteFindManyWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerFindManyArgs, TQueryFnData = Array<Prisma.WorkflowTriggerGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/findMany`, args, options, fetch);
}

export function useSuspenseFindManyWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerFindManyArgs, TQueryFnData = Array<Prisma.WorkflowTriggerGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerFindManyArgs, TQueryFnData = Array<Prisma.WorkflowTriggerGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/findMany`, args, options, fetch);
}

export function useFindUniqueWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerFindUniqueArgs, TQueryFnData = Prisma.WorkflowTriggerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerFindUniqueArgs, TQueryFnData = Prisma.WorkflowTriggerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/findUnique`, args, options, fetch);
}

export function useFindFirstWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerFindFirstArgs, TQueryFnData = Prisma.WorkflowTriggerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerFindFirstArgs, TQueryFnData = Prisma.WorkflowTriggerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/findFirst`, args, options, fetch);
}

export function useUpdateWorkflowTrigger(options?: Omit<(UseMutationOptions<(WorkflowTrigger | undefined), DefaultError, Prisma.WorkflowTriggerUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowTriggerUpdateArgs, DefaultError, WorkflowTrigger, true>('WorkflowTrigger', 'PUT', `${endpoint}/workflowTrigger/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowTriggerUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowTriggerUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkflowTrigger, Prisma.WorkflowTriggerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowTriggerUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkflowTrigger, Prisma.WorkflowTriggerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyWorkflowTrigger(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WorkflowTriggerUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowTriggerUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('WorkflowTrigger', 'PUT', `${endpoint}/workflowTrigger/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowTriggerUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowTriggerUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowTriggerUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertWorkflowTrigger(options?: Omit<(UseMutationOptions<(WorkflowTrigger | undefined), DefaultError, Prisma.WorkflowTriggerUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowTriggerUpsertArgs, DefaultError, WorkflowTrigger, true>('WorkflowTrigger', 'POST', `${endpoint}/workflowTrigger/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowTriggerUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowTriggerUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkflowTrigger, Prisma.WorkflowTriggerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowTriggerUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkflowTrigger, Prisma.WorkflowTriggerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteWorkflowTrigger(options?: Omit<(UseMutationOptions<(WorkflowTrigger | undefined), DefaultError, Prisma.WorkflowTriggerDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowTriggerDeleteArgs, DefaultError, WorkflowTrigger, true>('WorkflowTrigger', 'DELETE', `${endpoint}/workflowTrigger/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowTriggerDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowTriggerDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkflowTrigger, Prisma.WorkflowTriggerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowTriggerDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkflowTrigger, Prisma.WorkflowTriggerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyWorkflowTrigger(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WorkflowTriggerDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkflowTriggerDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('WorkflowTrigger', 'DELETE', `${endpoint}/workflowTrigger/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkflowTriggerDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkflowTriggerDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WorkflowTriggerDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerAggregateArgs, TQueryFnData = Prisma.GetWorkflowTriggerAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerAggregateArgs, TQueryFnData = Prisma.GetWorkflowTriggerAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/aggregate`, args, options, fetch);
}

export function useGroupByWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WorkflowTriggerGroupByArgs['orderBy'] } : { orderBy?: Prisma.WorkflowTriggerGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WorkflowTriggerGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WorkflowTriggerGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkflowTriggerGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkflowTriggerGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WorkflowTriggerGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WorkflowTriggerGroupByArgs['orderBy'] } : { orderBy?: Prisma.WorkflowTriggerGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WorkflowTriggerGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WorkflowTriggerGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkflowTriggerGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkflowTriggerGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WorkflowTriggerGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/groupBy`, args, options, fetch);
}

export function useCountWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WorkflowTriggerCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/count`, args, options, fetch);
}

export function useSuspenseCountWorkflowTrigger<TArgs extends Prisma.WorkflowTriggerCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WorkflowTriggerCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkflowTriggerCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/count`, args, options, fetch);
}
import type { TriggerType } from '@zenstackhq/runtime/models';

export function useCheckWorkflowTrigger<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; organizationId?: string; workflowId?: string; boardId?: string; triggerType?: TriggerType; enabled?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('WorkflowTrigger', `${endpoint}/workflowTrigger/check`, args, options, fetch);
}
